const express = require("express")
const router = express.Router()
const {verifyStudentTokens,enrollStudents,StripeIntegrationForEnrolment,getQuizesbyCourse,submitQuiz,getQuizById} = require("../controller/StudentController")
const {authorizedStudent} = require("../Middleware/Student")
const {getAllCourses} = require("../controller/CourseController")
router.post("/verifyStudentToken",verifyStudentTokens)
router.get("/getAllCourses",authorizedStudent,getAllCourses)
router.post("/enrollStudents",authorizedStudent,enrollStudents)
router.post("/stripeEnrolment",authorizedStudent,StripeIntegrationForEnrolment)
router.get("/getQuizzes/:courseId",authorizedStudent,getQuizesbyCourse)
router.post("/submitQuiz",authorizedStudent,submitQuiz)
router.get("/getQuiz/:quizId",authorizedStudent,getQuizById)
module.exports = router